version: '3.8'

services:
  # Development server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=skill-swap-dev-secret-key-2024
      - CLIENT_URL=http://localhost:3000
      - DATABASE_PATH=/app/data/skillswap.db
    volumes:
      - ./server:/app:delegated
      - /app/node_modules
      - server_data:/app/data
      - server_uploads:/app/uploads
    command: npm run dev
    networks:
      - skillswap-dev

  # Development client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm start
    networks:
      - skillswap-dev

  # Database viewer (optional)
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - skillswap-dev
    profiles:
      - tools

volumes:
  server_data:
    driver: local
  server_uploads:
    driver: local

networks:
  skillswap-dev:
    driver: bridge